### ISSUE TITLE
Saving the results

### ISSUE THREAD

**Issue by Dola47** [interpretml/interpret#161]
Hi All,

Is there is a way to save the results showing out of the show function as PDFs or in a  LaTeX format?

Thanks in advance.

**Comment by interpret-ml** [comment]
Hi @Dola47, 

Good question! Each of the graphs from the show function are Plotly figures, so you can save them using the Kaleido library that Plotly publishes (assuming your environment has Plotly 4.9+):

```pip install kaleido``` 

Once you've installed Kaleido, you can simply loop through all the objects in your explanation and write them to a variety of formats, including PDF. For example:

```python3
ebm_global = ebm.explain_global()

for key in range(len(ebm_global.selector)):
    fig = ebm_global.visualize(key)
    fig.write_image(f"images/graph_{key}.pdf")
```
which will produce a statically exported PDF of each graph in the global explanation. Of course, you can do the exact same thing with any type of explanation in Interpret. 

For more details on tweaking the image exports (ex: controlling height and width of the images), check out this documentation page: https://plotly.com/python/static-image-export/ . If you want the graphs to remain interactive, you can use the ```.write_html``` function instead of ```.write_image``` which will produce HTML files. Hope this helps, and please feel free to ask any other questions!

-InterpretML Team

**Comment by Dola47** [comment]
@interpret-ml  I have been trying doing the same, but whenever I do the fig.write_image command my Jupyter notebook kernel does not stop running and nothing is saved, any idea why this is happening?

**Comment by GaoyangLiu** [comment]
> > Hi @Dola47,
> > Good question! Each of the graphs from the show function are Plotly figures, so you can save them using the Kaleido library that Plotly publishes (assuming your environment has Plotly 4.9+):
> > `pip install kaleido`
> > Once you've installed Kaleido, you can simply loop through all the objects in your explanation and write them to a variety of formats, including PDF. For example:
> > ```python
> > ebm_global = ebm.explain_global()
> > 
> > for key in range(len(ebm_global.selector)):
> >     fig = ebm_global.visualize(key)
> >     fig.write_image(f"images/graph_{key}.pdf")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which will produce a statically exported PDF of each graph in the global explanation. Of course, you can do the exact same thing with any type of explanation in Interpret.
> > For more details on tweaking the image exports (ex: controlling height and width of the images), check out this documentation page: https://plotly.com/python/static-image-export/ . If you want the graphs to remain interactive, you can use the `.write_html` function instead of `.write_image` which will produce HTML files. Hope this helps, and please feel free to ask any other questions!
> > -InterpretML Team
> 
> @interpret-ml Thanks this is really helpful! Just a quick question - seems like the only plots for each feature is included here. How can I get the summary plot?
> 
> For whoever wants to save the plots by feature name instead of key, `ebm_global.selector["Name"][key]` will give you the corresponding feature name.

I am wondering how to save the summary plot, too. Did you get it?

**Comment by HLasse** [comment]
@GaoyangLiu @Chelsea-Z 
You can hack the summary plot by extracting the feature importances and feature names from the fitted EBM object and plotting them yourself:

```python
import matplotlib.pyplot as plt

feature_names = ebm.feature_names
feature_importances = ebm.feature_importances_

plt.bar(feature_names, feature_importances)
```
