### ISSUE TITLE
Question: Which hyperparameters to tune and how

### ISSUE THREAD

**Issue by alberto-oliveira** [interpretml/interpret#162]
Hello, I've been looking into performing hyperparameter tuning of `ExplainableBoostingRegressor´ and I've been wondering if you folks have any recommendation on (1) which EBM parameters to tune and (2) what are some adequate ranges for each of those parameters. Thank you in advance!

**Comment by interpret-ml** [comment]
Hi @alberto-oliveira , 

Sorry for the delay in getting back to you. In general, EBMs should perform reasonably well out of the box without any parameter tuning. At the cost of increasing training time, you can set the `interactions` parameter to a non-zero number, which will automatically detect and introduce several pairwise interaction terms in the model. This can significantly improve performance on some datasets, especially in the regression setting. For smoother graphs, you can also increase `outer_bags` and `inner_bags`. 

Changing `max_bins` and `min_samples_leaf` can also help regularize the model if you observe some of the graphs to be too jumpy on sparse regions of the data. In general, we recommend looking at the learned graphs from `explain_global()` and letting that guide your parameter tuning. Please let us know if you have any further questions!

-InterpretML Team

**Comment by NicoHambauer** [comment]
I have one question related to this topic with explain_gloabl(), specific if max_bins can influence how and how much of the data is used for the plotting of shape functions.
In the following 2 figures, I analyze EBM globally and plot the same X and y train Data from the data structure returned by explain_global() but with varying max_bin parameters:

max_bin = 256 (default):
![image](https://user-images.githubusercontent.com/58194361/141811150-7349ff45-8a91-4577-9010-64c2ee1a075f.png)

max_bin = 20000:

![image](https://user-images.githubusercontent.com/58194361/141807158-c5ee4895-2f27-45af-82b3-861f0c51fc3b.png)

The first two numbers show the 
1. max value of the x-axis at the current feature.
2. length of the array x / number of distinct values included plot along the x-axis.

Is this how I include more data to explain in the shape function or is it rather the wrong way but with the desired side effect since I thought max_bins would influence the actual model architecture.
How can I correctly control the range of the x axis / the max amount of distinct feature values per feature returned by explain_global().
