### ISSUE TITLE
Is EBM the same of GA2M?

### ISSUE THREAD

**Issue by navdeep-G** [interpretml/interpret#171]
* In the paper, https://arxiv.org/pdf/1909.09223.pdf, it mentions that EBM is faster than GA2M. However, they look to be the same model mathematically. Or is the "faster" due to the implementation in C++?

**Comment by interpret-ml** [comment]
Hi @navdeep-G  --

There are some relatively minor implementation differences, and some additions like multiclass, but for the most part EBMs are faster than the previous mltk (GA2M) implementation due to the efficient C++ implementation.  Rich Caruana from our current team, and Yin Lou who is on the InterpretML governance board, originally came up with the GA2M name.  We decided to rebrand it in part because the new C++ implementation also supports 3 way, and higher level interactions, so the “2” in GA2M was no longer accurate to the capabilities.  The higher dimensional interaction options are not exposed at the python level currently, but are implemented in the lower level C++ layers, and should be fully supported at a future date.  We intend to move away from the reference GA2M where it's necessary, the rebrand buys that flexibility to do so.

-InterpretML team

**Comment by aaronsnoswell** [comment]
Thanks for the clarification here - I came here wondering the same question. By the way, can I ask, how is "GA2M" read out-loud? I've been saying "Gam-Squared" but this isn't quite accurate.

**Comment by interpret-ml** [comment]
Hi @aaronsnoswell -- We spell out each letter and number, so: g-a-two-m.

As an update to the above, in the develop branch we now support GA3M, GA4M, GA5M, etc.  It's not on PyPI yet though.

-InterpretML team

**Comment by avilog** [comment]
@interpret-ml Thanks for this update!. Can EBM detect (n>2) feature interactions? or just fit them.  Does it use the data structure to fit them as it's explained in the "Accurate Intelligible Models with Pairwise Interactions" paper? (checking all combinations of cuts for all features with the lookup table).

**Comment by interpret-ml** [comment]
Hi @avilog -- Currently you only get 3+ ways interactions when you fully specify them via the interactions parameter.  Implementing 3+ way FAST is a minor change in the lower C++ levels, but we're a little less sure what a good way to expose automatic 3+ way interaction detection would be via our python interface since there are some controlling parameters that would need to be exposed, and we might want it to be partly user controllable during the fit process via some new API.

At some point, hopefully soon, we'll put out a standalone interaction detection API and maybe expose 3+ way FAST there first.  We'll probably pause there for a while and see what kind of feedback we get from the community before deciding how these should be made more generally available.

-InterpretML team
