### ISSUE TITLE
Importance of feature selection for EBM

### ISSUE THREAD

**Issue by hakeemo** [interpretml/interpret#179]
I was wondering if feature selection is a critical step in order for EBM to perform decently on a dataset with a lot of noisy features, since every feature is used in the algorithm.

**Comment by rodrigovssp** [comment]
#up

Em Qui, 29 de out de 2020 18:32, hakeemo <notifications@github.com>
escreveu:

**Comment by interpret-ml** [comment]
Hi @hakeemo & @rodrigovssp,

Good question. It depends, it isn't always critical to do an external feature selection step before running EBM in the event of noisy features. There's a number of moving parts within the algorithm that will try to suppress influence from a noisy feature at varying degrees of success. Upon saying that, empiricism rules the day and would recommend trying both alternatives, if you see it works well often within your domain - not all types of noise are equal and some preprocessing might capture noise better than learner can.

Will have to get back you on this issue for a more in-depth response. It's an interesting question that prompts debate on how boosting should be conducted for each stage: i.e. whether greedy feature selection should be conducted, use of cyclic boosting, etc. There are trade-offs abound, and much of this is still active research.

**Comment by rodrigovssp** [comment]
#up


Em sáb., 31 de out. de 2020 às 05:12, InterpretML <notifications@github.com>
escreveu:

**Comment by richcaruana** [comment]
Continuing the discussion --- with EBMs it's good to try first using all features to give the data and algorithm a chance to surprise you.  Then if any of the graphs look like they have little or no contribution to the model (i.e., the graph is near zero everywhere), or look like they have very high noise, then these features can probably be safely removed and the model retrained without them.  In other words, we would suggest using EBMs as part of the feature selection process, instead of using an external feature selection method that doesn't know how EBMs would use the features.  

Also, there's a tendency to think that as long as accuracy does not suffer, fewer features would yield a more intelligible model.  This is often not the case with EBMs.  If correlation among features allows a model to learn essentially the same I/O function with fewer features, we often find that the graphs of the models trained with fewer features are more complex and thus more difficult to understand.  If instead you allowed more features back in the model sometimes the individual graphs get cleaner and easier to understand even though there are more of them.  So fewer features is not necessarily more intelligible. 

Sometimes the model is a little less accurate when there are many features because of the classic bias vs. variance tradeoff: adding many features can increase variance and thus hurt accuracy.  But models like EBMs are not just about raw accuracy.  Intelligibility is very important, too.  You might be able to improve accuracy slightly in the 3rd decimal place by doing feature selection, but in the process you might eliminate terms from the model that are important for less frequent cases that are still important.  Eliminating the term doesn't hurt accuracy because it rarely applies, and it might help accuracy slightly by reducing variance a little (because your sample size isn't large enough to learn everything well), but if you remove the feature you won't learn what the model would have taught you about that feature, and those cases may now be "underserved" by the model.  The beauty of intelligibility is that you can see this happen.  If you do the same kind of feature selection in a black-box model the same thing happens, accuracy goes up slightly so you're happy, but in fact you just lost the ability to make accurate predictions for a small subgroup and don't even know it happened.  But there are times when a small increase in accuracy is more important than a loss in intelligibility or ability to serve small groups --- it all depends on the specific problem.

Perhaps the bottom line is that when using intelligible models like EBMs we encourage you to not only think about maximizing accuracy, but also about maximizing intelligibility and understanding, too, and from this point of view feature selection can be a two-edged sword.

**Comment by Soheil-Zangeneh** [comment]
> Continuing the discussion --- with EBMs it's good to try first using all features to give the data and algorithm a chance to surprise you. Then if any of the graphs look like they have little or no contribution to the model (i.e., the graph is near zero everywhere), or look like they have very high noise, then these features can probably be safely removed and the model retrained without them. In other words, we would suggest using EBMs as part of the feature selection process, instead of using an external feature selection method that doesn't know how EBMs would use the features.
> 
> Also, there's a tendency to think that as long as accuracy does not suffer, fewer features would yield a more intelligible model. This is often not the case with EBMs. If correlation among features allows a model to learn essentially the same I/O function with fewer features, we often find that the graphs of the models trained with fewer features are more complex and thus more difficult to understand. If instead you allowed more features back in the model sometimes the individual graphs get cleaner and easier to understand even though there are more of them. So fewer features is not necessarily more intelligible.
> 
> Sometimes the model is a little less accurate when there are many features because of the classic bias vs. variance tradeoff: adding many features can increase variance and thus hurt accuracy. But models like EBMs are not just about raw accuracy. Intelligibility is very important, too. You might be able to improve accuracy slightly in the 3rd decimal place by doing feature selection, but in the process you might eliminate terms from the model that are important for less frequent cases that are still important. Eliminating the term doesn't hurt accuracy because it rarely applies, and it might help accuracy slightly by reducing variance a little (because your sample size isn't large enough to learn everything well), but if you remove the feature you won't learn what the model would have taught you about that feature, and those cases may now be "underserved" by the model. The beauty of intelligibility is that you can see this happen. If you do the same kind of feature selection in a black-box model the same thing happens, accuracy goes up slightly so you're happy, but in fact you just lost the ability to make accurate predictions for a small subgroup and don't even know it happened. But there are times when a small increase in accuracy is more important than a loss in intelligibility or ability to serve small groups --- it all depends on the specific problem.
> 
> Perhaps the bottom line is that when using intelligible models like EBMs we encourage you to not only think about maximizing accuracy, but also about maximizing intelligibility and understanding, too, and from this point of view feature selection can be a two-edged sword.

Hi you made a great package but something about EBM is not clear to me. if we have correlated features (linearly and non-linearly) does it mean in summary we will see a smaller value for importance? I mean does it mean the true weight of independent phenomena will divide between that features or not?
