### ISSUE TITLE
Generic questions for EBM usage

### ISSUE THREAD

**Issue by Heringer-Epson** [interpretml/interpret#188]
Hi devs,

Could you please help with the following questions:

* Does EBM benefit from data scaling in the pipeline?
* Are there any recommendations for faster model training and/or for handling large datasets? I have attempted to train on 10M rows and 50 features, which took >6h. Currently, is there a way to improve this? e.g. coupling EBM with PySpark pandas UDF? 
* Does EBM benefit from hyperparameter optimization? If so, are some parameters known to be more relevant?
* Does EBM accept weights for model training?
* Aside from undersampling the majority class, are there any recommendations for dealing with imbalanced classes? Oversampling of the majority class leads to problems addressed in another issue (see https://github.com/interpretml/interpret/issues/187)

Thank you for your time!

**Comment by interpret-ml** [comment]
Hi @Heringer-Epson -- Here are our answers to your questions:

- EBMs do not benefit from data scaling.  Like other tree based methods, they only consider the ordering of the feature values.
- We do have some work in the pipeline to significantly improve the speed of the package, but these changes are not imminent.  There are some parameters like outer_bags and learning_rate which can be changed to speed up training, but in general we don't recommend doing that since we believe we've selected parameters which perform well in most settings
- EBMs generally don't benefit from hyperparameter optimization, but you can improve the predictions in many models by setting the interactions parameter to something higher than 0.  Interactions aren't enabled by default yet because they significantly increase the training time.
- We don't currently support weights, but it's in our backlog
- EBMs generally handle imbalanced data fairly well and don't require any special handling for these datasets.  If you believe that you have a dataset that isn't being handled well, please let us know!

-InterpretML Team

**Comment by Heringer-Epson** [comment]
Thank you again for the speedy response. Closing the issue as the questions have all been answered.

**Comment by interpret-ml** [comment]
I'll just add that our next release will be about 2x faster for classification (changes are already in our develop branch).  We do have much larger speed improvements on the horizon though.

-InterpretML team

**Comment by Heringer-Epson** [comment]
Replying to a comment above:

"EBMs generally handle imbalanced data fairly well and don't require any special handling for these datasets. If you believe that you have a dataset that isn't being handled well, please let us know!"

For the dataset I am using, which is a binary class at an imbalanced rate of 16%, I found that the AUC of EBM models are comparable with those from Spark's GBT (at around 0.81), which suggests that EBM is indeed handing the class imbalance well. I will note that for both models, the choice of how much to undersample the majority class leads to an important tradeoff: while the AUC remains somewhat constant, the precision and recall can vary greatly (between 0.84 and 0.40).
