### ISSUE TITLE
documentation for preserve or other generic function of this package

### ISSUE THREAD

**Issue by Arkarachai** [interpretml/interpret#198]
Do you have documentation for the `preserve` or other generic function of this package? I can't use `show` function, so I need to use preserve, but I can't find detail in your readthedocs.io

**Comment by interpret-ml** [comment]
Hi @Arkarachai --

We don't currently have formal documentation for our package since we've been making a lot of breaking changes to solidify the API.  While you can use preserve, we recommend testing out the inline visualization provider first in environments where show doesn't work.  The InlineProvider directly embeds visualizations in your notebook, and doesn't require spinning up a web server on a separate port. To do this, put the following at the top of your notebook:

``` python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

-InterpretML

**Comment by Arkarachai** [comment]
Thank you. I try that just now and I can finally see the output from "show". It looks great!! Would this have all the capability of "show" that we would have if we spin up a server?
  
Just FYI  I can't see the preserve though.
  preserve(ebm_global, 'Age'). ## show me nothing
  preserve(ebm_global, 'Age', file_name='global-age-graph.html') ## generate HTML locally
Anyhow, that is okay. I can just use show anyway.

**Comment by interpret-ml** [comment]
Hi @Arkarachai, 

Just wanted to update this issue: we have official documentation now at https://interpret.ml/docs/ . Future readers might be interested in some of the interactivity/visualization related documentation here: https://interpret.ml/docs/framework.html# 

Thanks!
-InterpretML Team

**Comment by Arkarachai** [comment]
That is great! I have been using it since we last discussed it, and I really enjoy it. Glad to hear the documentation comes out.
