### ISSUE TITLE
Can we linearly combine the results of two EBM regression predictions?

### ISSUE THREAD

**Issue by nightynighto** [interpretml/interpret#202]
Hi all,

I have what probably is a stupid question, but:

Say I've trained two EBM regression models, one for predicting output variable A, and one for predicting output variable B.

Both of these models use the exact same input variables, consisting of similar samples.

Now, if I also want to make a model that predicts A/B, could I just get the function by dividing model A and model B directly? Or would the result somehow be different than if I had a completely new model trained on a dataset that explicitly measures A/B (which I don't have, since I have A and B measured on very similar but slightly?

Also, if it is possible to just combine the results of two EBMs like that, how would the error propagation work? How can I get the error for the divided model?

Any help would be appreciated, thank you!

**Comment by richcaruana** [comment]
In the ideal case you'd have A and B for each case and then be able to train a model to predict A/B directly.  One advantage of that is that you can preprocess A/B if necessary to make the regression well behaved --- for example if B might sometimes be close to 0, then A/B could become very large, but you might not want those cases to dominate the learned function so you might use log(A/B) or Sqrt(A/B) or things like that to tame this kind of behavior.  But maybe that's not an issue with your data.

If you can't get A and B for each case, then the next best thing is probably what you were planning to do --- train separate models to predict A and B, and then divide the prediction of the A model by the prediction of the B model.  You still might have to worry about B becoming small and causing the prediction to blow up.  The only disadvantage of training separate models and doing the division afterwards is that optimizing squared error on the individual models does not necessarily optimize squared error on A/B, so the prediction accuracy might not be as high as it would be if you could train one model on A/B targets.  But it might still be pretty good depending on how well the model learns to predict A and B.

While combining the **predictions** from models trained to predict A and B is easy, it's not easy to combine the **models** themselves to create a new intelligible model for A/B because (a+b)/(c+d) is not equal to a/c + b/d so you can't just divide one graph of one model by one graph of the other model.  

Hope this helps!   -the InterpretML team.
