### ISSUE TITLE
Intercept

### ISSUE THREAD

**Issue by MassimilianoGrassiDataScience** [interpretml/interpret#207]
Just a simple clarification about the intercept in a classification task using ebm. Should it be interpreted as the logit when all predictors have value = 0, like in logistic regression? If so, value 0 in each feature should have a score close/equal to 0 in the `explain_global` plot.

Thanks again

**Comment by interpret-ml** [comment]
Hi @MassimilianoGrassiDataScience, 

Good question! EBMs are a bit different from logistic regression in that each graph is centered around 0. By that, we mean that EBMs ensure the mean prediction for each feature is 0 across the training data distribution. This keeps the models identifiable, and also has some nice properties like being able to completely "zero-out" or ignore features at prediction time without biasing the model's overall predictions. 

However, this ends up meaning that the predictors having a value = 0 is not a special case like it is in logistic regression, and EBMs will often learn a non-zero contribution for a predictor value = 0 (ex: Income = 0 might contribute -2 in an EBM, whereas in a logistic regression it would always contribute 0). 

Just like in logistic regression, the intercept should be the "base rate" of the data (the average of the target variable passed through the link function). However, the interpretation of the intercept changes slightly. Instead of the prediction the model will make when all the predictors are 0, it instead becomes the prediction the model will make when all the predictors are "average".

This centering operator is not unique to EBMs, and most GAM implementations do something similar. For a detailed discussion on this, check out this stackoverflow link: https://stats.stackexchange.com/questions/33785/centering-constraints-for-regression-specifically-gam

Thanks!
-InterpretML Team

**Comment by MassimilianoGrassiDataScience** [comment]
Thank you for your thorough reply! That is clear now. 

It is very interesting that missing values in the features may be handled natively by the model as in a (non-common) average imputation strategy.
