### ISSUE TITLE
Target Distributions: Poisson, Gamma, etc...

### ISSUE THREAD

**Issue by alptuzel** [interpretml/interpret#211]
Hello,

Thanks for the great work!

I have a question regarding the target variable distribution. In other Gam implementations there is target distribution specification: poisson, gamma, etc... Is there such an option in ExplainableBoostingRegressor? Do you plan to implement such a feature? And finally I wonder how it is handled now, is it assumed to follow a normal distribution?

Cheers.

**Comment by paulbkoch** [comment]
Thanks @alptuzel -- Currently we do not support alternate link functions, however it is in our backlog for future implementation.  You are correct that we currently assume a normal distribution through the use of the identity link.

I'm going to close this issue since we have another issue tracking alternative link functions and we'll post any updates there: https://github.com/interpretml/interpret/issues/137.
