### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by MainRo** [interpretml/interpret#215]
Hello, 

Following a previous question we had on deployment (#129), we implemented an EBM ONNX exporter.
The package is available on pypi and the github repo is here:
https://github.com/SoftAtHome/ebm2onnx

This is the first release, but all current features of EBM should be supported. If you feel this could be part of the interpretml organization we can consider moving it.

**Comment by interpret-ml** [comment]
Hi @MainRo, 

Thanks for bringing this to our attention -- `ebm2onnx` looks great! We had a brief chance to look through your repo, and we all think the code is well written and nicely structured. 

We love the idea of bringing ebm2onnx into the InterpretML organization, but just need to run it by our technical steering committee first. The InterpretML org has an independent governance structure, including people outside of Microsoft, and adding new projects into the org formally requires approval from our TSC. It's a bit of process, but the governance model is structured so that any projects brought into the org can maintain a large degree of independence and control (ex: choosing maintainers with commit rights for each project, etc.). 

If you're interested/available, we'd also be happy to meet with you sometime to chat about this. Either way, we'll present this issue at the next TSC meeting and reply back on this thread once we have an update. Thanks again for this fantastic contribution!

-InterpretML Team

**Comment by MainRo** [comment]
We're glad to see that you have some interest in this exporter! In any case, we are interested in talking with you so that we may share a view on its evolution and maintenance.

**Comment by interpret-ml** [comment]
Hi @MainRo, 

Sorry for the delay here! We're still working on bringing this through the TSC, but we'd love to meet and chat in the meanwhile. Do you mind reaching out to us at "interpret@micosoft.com" so that we can find a time to meet? 

-InterpretML Team

**Comment by interpret-ml** [comment]
Hi @MainRo -- Thanks again for your great contribution in this area and to SoftAtHome ( https://www.softathome.com/ ) for supporting OSS!  To update the community on developments, our Technical Steering Committee and SoftAtHome both approved the move of EBM2Onnx into the InterpretML Github organization, and it can now be found at:

https://github.com/interpretml/ebm2onnx

-InterpretML team
