### ISSUE TITLE
Exclude Features from 2nd Order Features Search

### ISSUE THREAD

**Issue by JoshuaC3** [interpretml/interpret#225]
When training an EBM the parameter, `interactions=10`, helps improve the predictive power of the model. However, in certain scenarios, this can cause problems, see [#184](https://github.com/interpretml/interpret/issues/184#issuecomment-822702385) as a single example. This is particularly true in regulated spaces and/or trying to understand feature importance and their affects on predictions.

To mitigate this we can set `interactions=0`, however, this is likely to reduce the predictive power of most models. Therefore, I propose a parameter which allows features to be excluded from the 2nd Order Feature Search. This would allow the creation of 2nd order features while also safeguarding the use of constrained or regulated features.

An simple and rough example the parameter could work as follows: `second_order_exclusion=[0, 1, 5, 21, 22]` or `second_order_exclusion=['feat_name_0', 'feat_name_1', ..., 'feat_name_22']`.

**Comment by interpret-ml** [comment]
Hey @JoshuaC3, 

This is a nice idea! As you point out, it's currently not possible to use the automated interaction detection with any restrictions -- it's currently all or nothing.  The main discussion point internally has been around the API for introducing this. 

In the past, we had a community contribution (https://github.com/interpretml/interpret/pull/66) which enabled support for "first_order_exclusion", i.e. allowing a feature to be skipped in training main effects but still be included in pairs. It's currently supported as a `mains` init argument in EBMs, and is used here: https://github.com/interpretml/interpret/blob/ac5e727498cbdcb6911444420343454b0f328a46/python/interpret-core/interpret/glassbox/ebm/ebm.py#L952-L957)

What we've mainly been discussing is: 

- The `mains` flag is currently _inclusion_-based -- you need to specify all the features you want included, not the ones you want skipped. On the other hand, it seems more common and practical to specify exclusions (as you've also suggested). Having two arguments that work in opposite ways is unintuitive/confusing, so we might need to change how the `mains` flag is currently used.
- Because the existing `mains` and proposed `second_order_exclusion` parameters are so similar, we're brainstorming ways of unifying them as a general `feature_exclusions` parameter which allows specifying both first and second order terms to skip. There's quite a lot of ways to approach this joint parameter design (e.g. a dictionary for mains/pairs, list of lists for each stage, etc.). and we're working through the relative tradeoffs of each. If none of these designs work out, we can always fall back to two separate parameters.

Wanted to share an update and hear your thoughts on this! We'll continue to update this thread as we make progress on our side. 

-InterpretML Team

**Comment by JoshuaC3** [comment]
Personally, the problem I see in having an inclusion based parameter, `second_order_constraints` is it is _slightly_ less intuitive - I would assume there to be fewer second-order-only variables than first-only or both.

This is how LightGBM does its feature interactions: [`interaction_constraints`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#interaction_constraints). This is a different type of constraint, namely, restricting any set features being in the same tree. If they are listed `interaction_constraints=[[1, 2], [1, 3]]` for example, this would restrict 2 and 3 from being in the same tree and use only [1, 2] and [1, 3] together.

That said, I feel the most intuitive solution would be rename and rework `mains` (quite an ambiguous name) to behave as `first_order_exlusions` and then add `second_order_exclusions` as proposed above. If ever desired and/or required, add an `interaction_constraints` which would either supersede/subside to `second_order_exclusions`, or throw a warning when there was a conflict.

Ultimately, whether you chose to go with inclusions or exclusions I am not so bothered. If it is named well then it would be clear how it works, especially if it has an example. I would be very happy to put together a notebook example to showcase this if/when it gets implemented.

**Comment by francescopisu** [comment]
Is there any update on this regard ?

**Comment by mtl-tony** [comment]
I recently tried implementing this since I had a problem in which I wanted certain variable to never interact and it seemed to work for me. With the updates of 0.3 it's a relatively easy adjustment. I was going to do a pull request when I cleaned my code a bit but I can share where to change it for now. 

https://github.com/interpretml/interpret/blob/33162306fe82e2c61d75db49b3c493f8b8099925/python/interpret-core/interpret/glassbox/ebm/ebm.py#L607-L618

From there I added a 'interaction_constraints' list in the EBMModel class.
https://github.com/interpretml/interpret/blob/33162306fe82e2c61d75db49b3c493f8b8099925/python/interpret-core/interpret/glassbox/ebm/ebm.py#L192

Then what you need to do is instead of passing `combinations(range(n_features_in), 2)` at line 613 you pass what fits your needs. I used the `interaction_constraints` and `feature_names_in` to make my combinations.

I'll probably do a pull request in the next few days.

**Comment by paulbkoch** [comment]
Hi @mtl-tony, @francescopisu & @JoshuaC3 -- I would like to propose a single parameter called "exclude=[...]" which will replace the existing "mains" parameter, and also handle the second order constraint case.  You could use it in the following ways:

exclude=[7, 9] # exclude mains of feature 7 and feature 9, but allow pairs that include these. Also accept tuples

exclude=[(7, x) for x in range(0, n_features)] # exclude pairs that include feature 7 

exclude=[(7, 9), (7, 11)] # exclude specific pairs

exclude= [7] + [(7, x) for x in range(0, n_features)] # exclude feature 7 entirely

**Comment by paulbkoch** [comment]
The exclude parameter which handles both main effects and pair exclusions has been implemented in the develop branch.  It will be in the next v0.4.0 release.

It works as described in my last message above.

**Comment by tszyan-bain** [comment]
hi @paulbkoch 

Thanks for releasing this feature.

Just to clarify:
1. when higher order interactions are included, do I need to specify them too? For example exclude = [(7,9,11)] for a 3rd order interaction exclusion.
2. Does the order of the index matter? What I mean is whether exclude=[(7,9)] will exclude also (9,7) as well as (7,9)?

**Comment by paulbkoch** [comment]
Hi @tszyan-bain -- 

1. If you specify the interactions explicitly and then exclude them it should work for pairs, triples, etc.  There's no way to currently get 3rd order interactions other than explicitly specifying them, so the only way to get to this scenario for 3rd order interactions would be to specify and then exclude them.

2. The order does not matter for exclusions.  exclude=[(7,9)] will exclude both (7,9) and (9,7).

**Comment by nkjays** [comment]
> The exclude parameter which handles both main effects and pair exclusions has been implemented in the develop branch. It will be in the next v0.4.0 release.
> 
> It works as described in my last message above.

Hi @paulbkoch, I am using v0.5.1 of interpret. I'm fitting an ebm and am trying to exclude a main effect (call this 'x') from my model while still including an interaction term. I noticed that when I do this, there is still two sets of bins in ebm.bins_ corresponding to 'x' (i.e. a set of main effect bins, and a set of interaction bins). There is no corresponding scores in ebm.term_scores_ for the main effect bins, but I don't understand why there is main effect bins for the excluded variable at all. Do you know why this is?

I also notice after specifying the exclude parameter, the order of ebm.term_scores_ no longer matches the order of ebm.bins_. the scores in ebm.term_scores_ are in the same order as ebm.term_features_, but ebm.bins_ is not in that order. This mismatch is causing issues in the code I've written to extract the scores into a csv format which was based primarily based off of the sample code here: https://interpret.ml/docs/ebm-internals-multiclass.html. 

I was wondering if this might be something worth looking into, or if you have any feedback that could help?

**Comment by paulbkoch** [comment]
Hi @nkjays -- On the first item you raised, we currently trim higher order bins that are not used, but we do not trim lower order bins.  To provide an example for others coming to this issue, you could have something like:

bins[feature_index] = [
   [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0],
   [2.0, 4.0]
]

If this feature wasn't included in any pairs, we'd simplify it to just:
bins[feature_index] = [[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]]

It would technically be possible to eliminate the lower order bin cut definitions if the feature wasn't included in the mains, but we'd need to fill that position with something, which would either be None, or maybe duplicate the pair bin cuts.  Either of those potential solutions seems more confusing for different reasons to me, so I'd lean towards keeping the current behavior despite this drawback.  If you want to modify the model yourself for things like privacy reasons you should be able to put anything you like in that position, and I think it would work.

On the second issue, you'll need to use the ebm.term_features_ attribute to solve the mismatch.  If you had a model with 10 features, no interactions, and were excluding the features 3 and 7, it would look like this:

ebm.term_features_ = [0, 1, 2, 4, 5, 6, 8, 9]

This exact scenario is covered here:
https://interpret.ml/docs/ebm-internals-multiclass.html

**Comment by nkjays** [comment]
@paulbkoch Thanks for clearing that up. Regarding the first point, how are the main effect bins determined? Is it that the EBM fits the main effect and then removes the scores at the end when exclude is specified? Or are the bins determined independently of the fitting process and the excluded main effect is not used at any point in fitting the model?

Thanks again

**Comment by paulbkoch** [comment]
@nkjays -- The bins are determined independently of the fitting process and the excluded main effect is not used at any point.  The default binning strategy is 'quantile' binning where the bins are chosen to have roughly the same number of samples in each bin.  You can choose other options via the feature_types parameter: https://interpret.ml/docs/python/api/ExplainableBoostingClassifier.html
