### ISSUE TITLE
ebm_local.data() is null ?

### ISSUE THREAD

**Issue by gaodianzhuo** [interpretml/interpret#227]
from interpret.glassbox import ExplainableBoostingClassifier

import numpy as np 
import pandas as pd
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from matplotlib import rcParams
rcParams['axes.spines.top'] = False
rcParams['axes.spines.right'] = False

X, y = make_classification(
    n_samples=10000, 
    n_features=20, 
    n_redundant=0,
    n_clusters_per_class=1,
    random_state=42
)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.01,random_state=1234)

ebm = ExplainableBoostingClassifier()

ebm.fit(X_train, y_train)

from interpret import show

ebm_global = ebm.explain_global()
show(ebm_global)
ebm_global.data()

ebm_local = ebm.explain_local(X_test, y_test)
# show(ebm_local)
ebm_local.data() #nothing why

**Comment by interpret-ml** [comment]
Hi @gaodianzhuo, 

Good question -- we could definitely document this better. The `.data` function signature is: 
```python3
def data(self, key=None):
```
`key` is used to index into the explanation and return the data for any sub-component of the bigger explanation object. For example, in the case of `ebm.explain_local(X_test)`, there is explanation data for each row in X_test. To retrieve data, the object needs to know which instance you'd like to retrieve data for. 

To access an explanation for the first instance in X_test, simply call:

```python3
ebm_local = ebm.explain_local(X_test, y_test)
explanation_data = ebm_local.data(key = 0) # Retrieves the explanation data for X_test[0]
```

If you'd like to retrieve explanation data for all items in X_test in one call, just set the key to -1: `ebm_local.data(key = -1)`. As a heads up, this API is also used for global explanations, where each key maps to a feature instead of an instance. Let us know if you have any further questions!

-InterpretML Team
