### ISSUE TITLE
How can I retrieve a confidence score from the global explanation graph of each feature for each feature value?

### ISSUE THREAD

**Issue by aman63** [interpretml/interpret#234]

**Comment by bverhoeff** [comment]
Thanks for creating the issue. My comment in another issue:

> Say I would want to try to somehow calculate confidence intervals for the final predictions of the model to have a measure of uncertainty of the prediction.

Would it be statistically sound to use abovementioned SD's to draw samples from a gaussian distribution for all features for a specific case and calculate many predictions of this case (adding all features up) so that I can calculate a SD of those predictions for that specific case?

If not, is there another direction of thought that leads to calculation of uncertainty of the predictions?

**So I think these are the questions:**

1) Is a standard deviation calculated by bagging data 8 times and training 8 models and averaging them representative for the distribution of uncertainty of the feature scores of a certain feature at certain feature values? (e.g. by calculating a normal distribution with average and SD).

2) Can we 'propagate' this uncertainty towards the final predictions by drawing from the respective abovementioned distributions as apropriate multiple times and calculating predictions multiple times as well, finally resulting in an average and SD of predictions for a certain case.

3) Currently there are no upper and lower bounds for interaction terms in the internal object. Would it be difficult to add these? Otherwise abovementioned method would only be possible without interaction terms

4) Most importantly, would abovementioned method be mathematically correct? I can imagine that this is the wrong place for that question. I could ask this at Stats Exchange / Cross Validated?

code example to illustrate line of thought:

`ebm_global = ebm.explain_global(name='EBM')


def feat_mean_sd(ebm_global, feature: int, value: float):
    name = ebm_global.__dict__["_internal_obj"]["overall"]["names"][feature]
    if " x " in name:
        return 0, 0, 0, name  # return zeros when interaction, not supported

    feat_dict = ebm_global.__dict__["_internal_obj"]["specific"][feature]
    vals = feat_dict["names"]
    means = feat_dict["scores"]
    upps = feat_dict["upper_bounds"]

    i = np.searchsorted(vals, value)
    if i == len(vals) - 1:  # in case new value above range X_train
        i -= 1
    sd = upps[i] - means[i]

    return means[i], sd, name


def draw_feature(ebm_global, feature, value):
    mean, sd, name = feat_mean_sd(ebm_global, feature, value)

    return np.random.normal(mean, sd), name


def pred_with_sd(feature_values):
    samples = []

    for sample in range(128):
        pred = 0
        for f in range(len(feature_values)):
            pred += draw_feature(ebm_global, f, feature_values[f])[0]
        samples.append(pred)

    return np.mean(samples), np.std(samples)


for i in range(5, 10):
    feature_values = X_test.iloc[i, :].values
    samples = pred_with_sd(feature_values)
    print(f"samples (1st): mean = {samples[0]:.3f}, sd = {samples[1]:.3f}")
    samples = pred_with_sd(feature_values)
    print(f"samples (2nd): mean = {samples[0]:.3f}, sd = {samples[1]:.3f}")`


Results with KDD2015 dropout data:

samples (1st): mean = 1.029, sd = 0.081
samples (2nd): mean = 1.040, sd = 0.077
samples (1st): mean = 1.310, sd = 0.068
samples (2nd): mean = 1.312, sd = 0.063
samples (1st): mean = 0.493, sd = 0.227
samples (2nd): mean = 0.505, sd = 0.220
samples (1st): mean = 0.664, sd = 0.104
samples (2nd): mean = 0.655, sd = 0.095
samples (1st): mean = 1.022, sd = 0.080
samples (2nd): mean = 1.041, sd = 0.084

**Comment by interpret-ml** [comment]
Hi @aman63, 

Good question! You can access these through the `.data()` method on any global explanation. For example:

```python3
ebm_global = ebm.explain_global()
graph_data = ebm_global.data(0)  # Gets graph related info for 0th feature -- swap input for different features
```
This returns a dictionary, with different graph-related information stored as parallel arrays. The upper and lower bounds can be accessed with:

```python3
# Extract upper and lower bound info
graph_data['upper_bounds']
graph_data['lower_bounds']
```

and the main x and y axis values are:

```python3
graph_data['names']  # x-axis values -- numbers for numeric features, strings for categorical
graph_data['scores']  # learned EBM effect
```

Outside of the global explanation object, the confidence scores are also stored on the ebm in the `term_standard_deviations_` property. The confidence bounds are symmetric, so this property only contains the value we add and subtract from the main effect graph to get the full interval for each bin. 

Hope this helps, and let us know if you have further questions!
-InterpretML Team
