### ISSUE TITLE
ebm memory issues

### ISSUE THREAD

**Issue by SoulEvill** [interpretml/interpret#251]
I am trying to run the hyperparameters search on EBM and using the hyperopt but I have noticed each iteration will increase the memory usage and wondering if there is a way to clear the memory usage of previous model. thanks a lot!

**Comment by interpret-ml** [comment]
Hi SoulEvil --

Can you give us an idea how big your data is and how much the memory requirements increase each iteration?  We haven't noticed any memory leaks in the native code and we do run memory checkers as part of our build (valgrind & ASAN) which should normally catch even small memory leaks.  Some growth in memory usage is normal up until a point due to things like memory fragmentation.  It's probably also safe to assume the hyperopt code would be holding some amounts of memory as well.

-InterpretML team

**Comment by interpret-ml** [comment]
Closing this for now.  Please reopen if there is more information regarding memory leakage.

-InterpretML Team

**Comment by aydindemircioglu** [comment]
i am running into the same problem, it seems, but with optuna instead of hyperopt. 
unsure how to debug this. i am running on 50 datasets, each dataset runs 29 trials,
in each an EBM is called. i am running this in parallel with joblib, with 8 cores.
it started with roughly 40 gb, but now takes around 94 gb, after around 5h run time.

unsure how to  debug this.

**Comment by aydindemircioglu** [comment]
ok, i my case the dataset has 577 samples with a dimension of 4070. 
EBM needed around 32gb for this.
using it in parallel crashed due to insufficient memory.

**Comment by paulbkoch** [comment]
Hi @aydindemircioglu -- 32gb is surprisingly large for a dataset with 577 samples.  When you say a dimension of 4070 do you mean it has 4070 features?  Can you post the hyperparameters that you're using when it takes 32GB?  To give some context, my rough calculation says this dataset should take something in the 60 megabytes range, not in the gigabytes.  Also, is this dataset public, and what version of interpret are you using?

**Comment by aydindemircioglu** [comment]
hi @paulbkoch, you can find the dataset BraTS-2021 here [BraTS-2021](https://github.com/aydindemircioglu/radMLBench/blob/main/datasets/BraTS-2021.gz).  Its a gzipped csv file. I did not change any of the hyperparameters, and create a classifier like this  `clf = ExplainableBoostingClassifier()` . I use interpret==0.6.1. Am not sure, if the optune package around does any harm, will test later, if this also happens if i do not use optuna, and just call EBM directly.

**Comment by aydindemircioglu** [comment]
ok, i think i have a minimal example (with another dataset which leaked even more memory, see repo abve)

```from interpret.glassbox import ExplainableBoostingClassifier
import radMLBench

def executeCV (dataset):
    X, y = radMLBench.loadData(dataset, return_X_y = True, local_cache_dir = "./datasets")
    cvSplits = radMLBench.getCVSplits((X,y), num_splits=10, num_repeats=1)
    for i, (train_index, test_index) in enumerate(cvSplits):
        clf = ExplainableBoostingClassifier()
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        clf.fit(X_train, y_train)
        y_prob = clf.predict_proba(X_test)[:, 1]
    pass


dataset = "UCSF-PDGM"
executeCV(dataset)
```

this started normal and then started to leak memory linearly (i stopped, else i think i would take at least 60gb ram)

![memory_usage](https://github.com/interpretml/interpret/assets/4368505/178e8e81-ddc0-42d2-b0fe-28310423cad1)

**Comment by paulbkoch** [comment]
What's radMLBench?

**Comment by paulbkoch** [comment]
Thanks for reporting this @aydindemircioglu.  Can you try the following:

1) add "import gc" at the top and "gc.collect()" inside the for loop.
2) Try another classifier, like XGBoost or anything else

**Comment by aydindemircioglu** [comment]
will try, but i had SVM,RF,LR running in parallel with 30 cores, with the same data, without any problems.

**Comment by aydindemircioglu** [comment]
added `gc.collect()` at the end of the loop, but no changes at all, same memory pattern.

**Comment by paulbkoch** [comment]
Hi @aydindemircioglu -- I'm pretty sure I know what is going on here.  The second dataset has 7,106 features, which means it has 25,244,065 possible pair combinations.  For each pair combination we use a few python objects.  Even if the python objects used only 100 bytes per pair, it would still take 2.5 GB to store them all.  We also run this in parallel with one process per core, so that increases the memory requirement by the number of cores you have.  I don't believe there is a leak because this memory will eventually be released.  It just consumes a lot currently.

Thinking through resolutions: we may need to modify the EBM algorithm to handle these kinds of datasets differently.  Perhaps we should restrict pairs to the top 1000 main effects.

If you're highly motivated to solve this today, there is an interaction detection API that you could use for this:
https://interpret.ml/docs/python/api/measure_interactions.html

Otherwise, you could try fitting only on the mains by setting interactions=0.  With 419 samples, I think interactions are unlikely to be critical.

**Comment by aydindemircioglu** [comment]
you might be right about that this is no memory leak, but i am not sure.
first, i misread my plot, and thought the slight dip in memory is because
the next fold was being computed, so it did look like during the second fold 
EBM leaks memory linearly. but that was still the first fold. i recomputed and
only stopped after the first fold. this is the memory consumption:
 
![memory_usage](https://github.com/interpretml/interpret/assets/4368505/a0dea57e-8ad2-4f9e-9c7f-7b7b2e8478e5)

i find that spooky that EBM takes 80gb for that dataset. 
then, i might be mistaken, but i still have the feeling that in the second fold
the memory consumption starts a few GB "higher" than the first fold.
so am not fully sure about ruling out memory leaks. but thats really a guess.
someone should try to reproduce, possibly in a clean environment.
 
thanks for the quick solutions, but i used EBM only out of curiosity,
to compare if it can replace the "usual" classifiers.

**Comment by aydindemircioglu** [comment]
one more comment: when the memroy is full, ONE process seems to hook up
most of the memory, so there is one process taking say 50% (could be 40GB then), 
and a lot of other threads only using 2% of memory. maybe this could be helpful.
