### ISSUE TITLE
Interaction Heatmap min and max values are global

### ISSUE THREAD

**Issue by lukedex** [interpretml/interpret#271]
Hello,

I've found that when using explain_global() and looking at interaction terms the heatmap colouring is always one sided. When looking into explain_global().['data'] it appears the Z_max and Z_min are not relevant to that factor at all. When I try this for different interaction factors the Z_max and Z_min always remains the same.

For example:
I'm getting Z values between -0.002 and 0.003, but my Z_max is 0.055 and Z_min is -0.06. 

Obviously not a huge issue but all my heatmaps are basically one shade due to this. Would be great if it's an easy fix.

Luke

**Comment by interpret-ml** [comment]
Hi @lukedex -- 

Good question! There's a parallel discussion about this here: https://github.com/interpretml/interpret/issues/236 where we discuss the motivation and possible options with @bverhoeff. You might find it interesting to read through!

There is a relatively simple way to set your own ranges by modifying the global explanation objects. Here's a quick code snippet that updates the interaction graphs to have new min/max scale ranges that you might find useful:

```python3
def modify_interaction_ranges(ebm_global, min_heatmap_val, max_heatmap_val):
    for data_dict in ebm_global._internal_obj['specific']:
        if data_dict['type'] == 'interaction':
            data_dict['scores_range'] = (min_heatmap_val, max_heatmap_val)
        
# Example of how to use it
ebm_global = ebm.explain_global()
modify_interaction_ranges(ebm_global, -1, 1)
show(ebm_global)
```

Running this example function rescales the interaction plots to be from (-1, 1) instead of the min/max of the entire model. 

Before: 

![image](https://user-images.githubusercontent.com/50031429/128424783-7952e0cc-e1e6-443d-8138-a840afa5c76a.png)


After:

![image](https://user-images.githubusercontent.com/50031429/128424800-53f8060b-31ff-496d-9c4d-50ce6fd1ec8b.png)



Hope this helps!
-InterpretML Team

**Comment by lukedex** [comment]
I did try and search through the issues but must of missed 236. That's great thank you! 

I'm assuming I could modify the function to use the actual min and max of the given interaction Z values as well correct?

**Comment by lukedex** [comment]
Missed the other issue- thank you! 
I'll mark this closed now.
