### ISSUE TITLE
question about EBM training process

### ISSUE THREAD

**Issue by shjustinbaek** [interpretml/interpret#310]
Hi, I have a question about the EBM training process when interaction term is involved.

I have been reading literature describing EBM, and i am confused about how exactly are the individual boostong trees trained when interaction term is involved.

https://www.cs.cornell.edu/~yinlou/papers/lou-kdd13.pdf

I would like to know if the following description is correct:
1. first FAST algorithm is used to rank interaction term by importance
2. then we choose how many interaction term to include
3. training begins:
    each training iteration is as follows:
    a. boosting trees are trained and each tree can only use 1 feature to the residual of previous tree
       (each feature gets a tree that uses it as the feature to predict target)
    b. when trees that uses 1 features are all trained, interaction term trees are trained. (that uses 2 features to predict residual of previous trees)

    visually it would look something like this
![image](https://user-images.githubusercontent.com/46898478/145743659-65b4ca2c-fe50-4bd3-8a59-ac1197e15975.png)

    the iteration(a,b) above is then repeated M times.

This is how i understood the paper's description of interaction term inclusion in EBM.
However, i found the descriptions in the paper a little vague and think i might have misunderstood.
I would love to know if I understood correctly.

Thanks in advance for the help
Really appreaciate library, thank you!

**Comment by xingzhis** [comment]
Hi,

I am also curious about this and I think I understood it differently. It would be great if the InterpretML team could give us some clarification.  
In your description, the 2-feature trees are _jointly_ trained with the 1-feature trees in each iteration, but I wonder if it is instead _sequentially_ trained, i.e.  

1. Train with only 1-feature trees.  
2. Use FAST to detect the top k pairs.  
3. Train 2-feature trees according to the pairs against the residual of the 1-feature trees.  

In the [InterpretML: A Unified Framework for Machine Learning Interpretability](https://arxiv.org/pdf/1909.09223.pdf) paper it said

> EBM is a fast implementation of the GA2M algorithm (Lou et al., 2013), written in C++ and Python.

and in the [Intelligible Models for HealthCare: Predicting Pneumonia Risk and Hospital 30-day Readmission](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/KDD2015FinalDraftIntelligibleModels4HealthCare_igt143e-caruanaA.pdf) paper it said

> GA2M builds the best GAM first and then detects and ranks all possible pairs of interactions in the residuals. The top k pairs are then included in the model (k is determined by cross-validation).

and in the [Accurate Intelligible Models with Pairwise Interactions](https://www.cs.cornell.edu/~yinlou/papers/lou-kdd13.pdf) it said

> With FAST, we can quickly rank of all pairs in Z, the remaining pair set, and add the best interaction to the model. However, refitting the whole model after each pair is added can be very expensive for large high-dimensional datasets. Therefore, we propose a two-stage construction approach.  
> 1. In Stage 1, build the best additive model F in H1 using only one-dimensional components.  
> 2. In Stage 2, fix the one-dimensional functions, and build models for pairwise interactions on residuals.  

If I understood it correctly, EBM implements FAST/GA2M, which first trains a GAM and then trains the interactions against its residual, rather than retraining the main effects and interactions together. This is not as accurate but requires less computational time.

Thank you for asking this question and look forward to clarifications from the InterpretML team!

**Comment by interpret-ml** [comment]
Hi @shjustinbaek & @xingzhis --

The description provided by xingzhis is correct.  We first train the mains (1 feature trees), then run FAST on the residuals.  We rank the FAST results within each outer bag and then take the average rank as the score for each potential pair.  The top N pairs are selected and boosted on to complete the model.

This is an area where we've made some changes since the original papers.  It used to be that we'd select different pairs for each outer bag and then we'd boost them separately.  We'd then rank them and choose the final pairs.  After picking the final pairs we'd throw away the previous pair boosting and we'd re-boost on the globally selected pairs.  Benchmarking indicated that we could use a simpler method of picking the pairs and then boosting just once, which saves time during fitting, and made the code simpler.

This is also an area where we could see making further changes in the future.  It's possible there could be some benefit in boosting the mains and pairs together, but we haven't run those experiments yet.

-InterpretML team

**Comment by shjustinbaek** [comment]
@interpret-ml 
Thanks for clarifying!
I will close this issue since my question is fully answered
