### ISSUE TITLE
Request for better documentation of what Humanized Quantile Binning is

### ISSUE THREAD

**Issue by dehdari** [interpretml/interpret#324]
Can someone please document briefly what _humanized_ quantile binning exactly is?  Going through the codebase it's not clear what it is, and googling doesn't elucidate it either.  Thanks.

**Comment by interpret-ml** [comment]
Quantile binning doesn't consider how many decimal places there are in the values that separate continuous features into bins.  Humanized quantile binning attempts to round to shorter floating point numbers.  An example will help:

Let's say we have a feature with the following 4 values and we ask for 2 bins:
1.1
2.718281828459045
3.141592653589793
70

Quantile binning will take the average between 2.718281828459045 and 3.141592653589793, yielding a bin separation value of 2.929937241024419.  Humanized quantile binning will choose 2.9 instead.  Other than a slight shift in the separation point, both methods will generate identical models since humanized quantile binning only rounds to the number of decimals that permit it to maintain the same bins as quantile binning.

-InterpretML Team

**Comment by dehdari** [comment]
Ok that makes sense, thanks. It's sort of a (lossless) rounded quantile binning. Is it possible to get the gist of what you wrote somewhere in the official documentation, so others know?

Also, while it would result in identical trained models, isn't it the case that there can be different predictions at inference time?  Probably mostly negligible, but just so I understand correctly.

**Comment by interpret-ml** [comment]
Yes, you are correct that it can slightly change predictions at inference time.  In the example above that would happen if the feature had a value of 2.91.

I've updated the documentation to describe this, and also renamed this parameter to 'rounded_quantile' to better describe its effect.  This change is currently in our develop branch and will be updated in our next release.

-InterpretML team
