### ISSUE TITLE
LimeTabular with mode='classification' gives an error

### ISSUE THREAD

**Issue by HakkaTin** [interpretml/interpret#360]
When using the lime library directly the following code works ok, which uses "model_1.predict_proba":

---------------------------------------------------------------------------
import lime
from lime import lime_tabular

explainer = lime_tabular.LimeTabularExplainer(
    training_data=df_training_xy[feature_names],
    feature_names=feature_names,
    class_names=['not-good', 'good'],
    mode='classification',
    discretize_continuous=False)

exp = explainer.explain_instance(
    data_row=df_training_xy[feature_names].iloc[1], 
    predict_fn=model_1.predict_proba
)

---------------------------------------------------------------------------

But when trying to use LimeTabular it gives an error even though I'm still using the same "model_1.predict_proba" to get the predicted probabilities. 

---------------------------------------------------------------------------
seed = 4221
lime_2 = LimeTabular(predict_fn=model_1.predict_proba,
                     data=df_training_xy[feature_names],
                     random_state=seed,
                     discretize_continuous=False,
                     mode='classification')

df_to_explain = df_training_xy[feature_names].head()

lime_2_localexplain = lime_2.explain_local(df_to_explain)

--> Gives the error:
NotImplementedError: LIME does not currently support classifier models without probability scores. If this conflicts with your use case, please let us know: https://github.com/datascienceinc/lime/issues/16

**Comment by paulbkoch** [comment]
Hi @HakkaTin -- This seems like a question better posed in the LIME repo.  Looking briefly at their code though at https://github.com/marcotcr/lime/blob/38a36464a45967bb44c4c9e60db4ef0d62d2cc02/lime/lime_tabular.py#L367 it appears predict_proba is returning a 1D array instead of a 2D array which is causing this exception.  I'm not sure if that's an issue with the predict_proba function or the call to LIME's internal self.__data_inverse function returning something unexpected.
