### ISSUE TITLE
Unable to connect "can’t establish a connection to the server at 127.0.0.1:7558"

### ISSUE THREAD

**Issue by KalinNonchev** [interpretml/interpret#366]
Hi,

thank you for developing this package!
I am trying the following:
```python
ebm = ExplainableBoostingClassifier(random_state=seed)
ebm.fit(X_train, y_train)

ebm_global = ebm.explain_global()
show(ebm_global)
```

which results in:
```
Unable to connect

Firefox can’t establish a connection to the server at 127.0.0.1:7558.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

I am using jupyter lab server and tried already changing the port, but then the interpret server port is also changing.
Could you help me with this?

Best,

**Comment by munozariasjm** [comment]
Hi there!
I can note the show element is in fact a Dash component. Thus, I would try to try something from [https://github.com/plotly/jupyter-dash](https://github.com/plotly/jupyter-dash).

Hope it works :)

**Comment by paulbkoch** [comment]
Hi @KalinNonchev -- Some cloud environments do not allow access to a flask server.  In those cases we recommend using the Inline Renderer.  Our documentation describes how to make this change:

https://interpret.ml/docs/deployment-guide.html?highlight=inlineprovider#interpret.provider.InlineProvider

Code:
```
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
set_visualize_provider(InlineProvider())
```

Closing for now since I believe this should fix this issue, but please re-open if it doesn't work.
