### ISSUE TITLE
Specify Lasso vs. LinearRegression somewhere

### ISSUE THREAD

**Issue by wnechtman** [interpretml/interpret#373]
Not a huge issue, but took me a while to figure out that the glassbox.LinearRegression model using Lasso. I thought the model was broken because my data was fit so poorly compared to sklearn.LinearRegression. Also, there is no inherited alpha parameter unless specified on instantiation. When setting alpha=0 to perform "linear regression", gets UserWarning ```With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator```.

I found little help with this and think at least documentation should be better. When you search ```Lasso``` in the repository, there are only 2 mentions, both are in the definition of the linear_class. Likewise on the website, the only hit for searching Lasso is in the api definition. Maybe just specify that the default linear_class is Lasso at the minimum.

**Comment by paulbkoch** [comment]
Hi @wnechtman -- Thank you for reporting this!  I can see why this was confusing.  Since the majority of people are not going to read the documentation, I've decided instead to make the default the more expected LinearRegression class.  It's possible to change this back to Lasso using the linear_class parameter if Lasso is still desired.

change: https://github.com/interpretml/interpret/commit/57c5449428ec6f5a868f6f31a83517867b3760cb
