### ISSUE TITLE
Cannot use ExplainableBoostingRegressor in Python script

### ISSUE THREAD

**Issue by maoding** [interpretml/interpret#388]
Hello interpret team,

I have recently discovered `interpret`  and I would like to test it in some pipelines for model evaluation.
My first steps were using `interpret` interactively in Jupyter which worked fine.
Now I try to move the Python script files.

For me it seems that I cannot properly train an `ExplainableBoostingRegressor`. See the following minimal example for Python `3.8` and `interpret=0.3.0`.

Content of `script.py`:
```python
from interpret.glassbox import ExplainableBoostingRegressor
from sklearn.datasets import load_iris

iris = load_iris()

X = iris["data"]
y = iris["target"]

ebm = ExplainableBoostingRegressor()
p_before = ebm.get_params()
ebm = ebm.fit(X, y)
p_after = ebm.get_params()
print(p_before == p_after)
```
Running `python script.py` yields a `True`. So it seems parameters are not updated and the model is not trained.

What am I doing wrong? How can I circumvent this?

**Comment by paulbkoch** [comment]
Hi @maoding -- get_params should return the parameters set in the __init__ function.  Calling fit should not change those, so this is the result that I would expect.  Try calling the predict function, or alternatively something like print(ebm.term_scores_)

**Comment by maoding** [comment]
Hello @paulbkoch ,
I think I can partly agree that some key value pairs in `get_params()` are not altered. Although there are others I would expect to be changed after calling `fit`, e.g. `feature_names`.

The output of `get_params()`:
```python
{'binning': 'quantile',
 'early_stopping_rounds': 50,
 'early_stopping_tolerance': 0.0001,
 'feature_names': None,
 'feature_types': None,
 'inner_bags': 0,
 'interactions': 10,
 'learning_rate': 0.01,
 'mains': 'all',
 'max_bins': 256,
 'max_interaction_bins': 32,
 'max_leaves': 3,
 'max_rounds': 5000,
 'min_samples_leaf': 2,
 'n_jobs': -2,
 'outer_bags': 8,
 'random_state': 42,
 'validation_size': 0.15}
```

The problem arises down the road e.g. using `ebm2onnx`'s `to_onnx()` which relies on `feautre_names`, see
https://github.com/interpretml/ebm2onnx/blob/master/ebm2onnx/convert.py#L86.

So am I treating this object anyhow wrong?

**Comment by paulbkoch** [comment]
Hi @maoding -- Ok, I see where you are coming from now.  Interpret 0.3.0 is a fairly big breaking change from previous versions.  Ebm2Onnx has not yet been updated to work with InterpretML 0.3.0, so if you want to use it today you'll need to use our older version 0.2.7 for now.  We've talked with the developer for that package (MainRo) and he has updated code that should mostly work with 0.3.0, but I'm unsure what his timeline for releasing it is.  I'd raise an issue in Ebm2Onnx if you feel that you need to use the latest InterpretML and would like more information.

Getting back to InterpretML: Unfortunately, the interface is indeed a bit confusing with regards to feature names.  We adhere to the scikit-learn API though, and that comes with some requirements that we can't (or shouldn't?) avoid.  scikit-learn has the following requirements:
1) Parameters passed into the init function are supposed to be stored unchanged as attributes with the exact same name as passed to init.
2) scikit-learn now has a feature names API as of version 1.0.  That introduces several requirements, in particular the requirement that we have a feature_names_in_ attribute that stores the fitted feature names.  See: https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep007/proposal.html

So, what does all this mean in practice?  We accept a feature_names parameter in our init function in order to give names to things like numpy array columns that do not originally have them.  Per scikit-learn, we should record the feature_names exactly as passed to us without modification.  So, by default the feature_names attribute should be None.  On the call to fit though, we record the names that we got, either copied from self.feature_names, or from Pandas, in the feature_names_in_ attribute per scikit-learn's API.  You should almost always be ignoring the feature_names attribute and just use the feature_names_in_ attribute instead.

Our previous version 0.2.7 was less scikit-learn compliant and did change some of the attributes like feature_names in the fit function.  We got away with this for a while, but I think on balance having higher levels of compliance is the better long-term course for us, especially as SLEP007 (the feature name API) sees more adoption.

**Comment by maoding** [comment]
Ah, thank you @paulbkoch.
So first I made a confusion with using the library in an interactive mode and then I adressed the problem at the wrong place.

I will fix this for the moment by pinning the versions:
```
interpret==0.3.0
interpret-core==0.2.7
ebm2onnx==1.3.0
```
Of course this is only a short term solution until `ebm2onnx` adapted to aforementioned changes.

Thanks for the indepth details about the breaking changes making `interpret` `scikit-learn` compliant.
