### ISSUE TITLE
Global decision rules from EGB

### ISSUE THREAD

**Issue by lucazav** [interpretml/interpret#389]
Is it possible to get decision rules from a trained EGB? A `get_dump()` method like the one implemented in XGBoost would be also useful.

**Comment by paulbkoch** [comment]
Hi @lucazav -- I'm assuming you meant EBM instead of EGB?  Technically you could output a set of decision rules for an EBM, however they would be so long that a human wouldn't be able to understand them.  If you want to get a dump of the internals of an EBM there is an unsupported function in the latest release called _to_json that might be interesting to you.  You can control the complexity of what is output with the properties parameter, with options of: 'minimal', 'interpretable', 'mergeable', 'all'.

https://github.com/interpretml/interpret/blob/f4a3f08cb95c3c99eb389a2a86e4f76a36af3395/python/interpret-core/interpret/glassbox/ebm/ebm.py#L1082

There's also the external tool ml_2_sql that has the ability to export SQL statements, which would be similar to decision rules I would guess.

https://github.com/kaspersgit/ml_2_sql

**Comment by lucazav** [comment]
Thank you, @paulbkoch! I'll explore the features you mentioned here.

**Comment by paulbkoch** [comment]
Hi @lucazav -- In terms of versioning issues here, _to_json is only available using Interpret 0.3.0.  ml_2_sql will only work with Interpret 0.2.7.
