### ISSUE TITLE
Question: Are images a part of the roadmap of this projects?

### ISSUE THREAD

**Issue by momegas** [interpretml/interpret#404]
Question: Are images a part of the roadmap of this projects?
Do you need help in implementing algos for images?

**Comment by paulbkoch** [comment]
Hi @momegas -- We're intrigued by your question.  What kinds of image interpretability algorithms did you have in mind?

Currently, our own focus has mostly been towards improving the EBM aspects of the package since that's a unique component that we invented in Microsoft Research and there's still a lot more to do in that area.  We are however not opposed in general to adding new interpretability techniques, especially if that effort would be mostly undertaken by someone motivated to improve interpretability in general.

**Comment by momegas** [comment]
I may be missing something. For example, I see only SHAP and Lime for tabular data. These algos can be used for images as well. This is what im referring to. Me and my team may be interested in contributing.

**Comment by paulbkoch** [comment]
Hi @momegas -- Interpretable image algorithms are still a rich area of research today.  If you're interested in contributing something in this space we'd be happy to have that conversation.  Send us a message at interpret@microsoft.com and we can set something up.
