### ISSUE TITLE
Question about the importance of subsets

### ISSUE THREAD

**Issue by master032** [interpretml/interpret#405]
Hi,

I found the code to calculate the importance of subsets in the example. I found that the importance of subsets seems to be the average of the absolute values of the global importance of all the features in the subset in Interpretml.

`def compute_group_importance(term_list, ebm, X, contributions=None):
    abs_sum_per_row = np.empty(len(contributions), np.float64)
    for i in range(len(contributions)):
        sum = 0.0
        for j in term_group_indices:
            sum += contributions[i][j]
        abs_sum_per_row[i] = abs(sum)

    return np.average(abs_sum_per_row)
`

I have two questions about the calculation of subset importance:

1. Is there a theoretical basis for this method of adding importance directly? Can the sum of the importance of different features represent the importance of the whole subset? Should other more complex intersections be made for the features in the subset?

2. I am trying to calculate the local importance of a subset. Is there a relevant calculation method for interpretml?

Looking forward to your reply

Thanks

**Comment by paulbkoch** [comment]
Hi @master032 --

There are two reasons for having term/feature group importances.  One is that features can often be corelated with one another, and that creates problems for all methods when calculating the importance of the features individually.  Let's say that I have two positively correlated features.  In fact, to illustrate, imagine that we took one feature and we made an exact copy of it in our dataset.  There isn't a perfect way to handle this situation since you can tradeoff importance between the two features without any change in the predictions, but the EBM will generally handle this by splitting up the contribution equally between these two features.  The end result is that each feature will have half the feature importance that it would if we had eliminated one of the duplicates.  This is an example of extreme/perfect correlation, but a similar problem occurs whenever there is strong correlation among a group of features, which there often is. 

Group importance can partly resolve this by grouping features together that you suspect are correlated.  Note that group importance does not change the prediction of the model in any way, it just adds groups of features to the summary of feature importance.  In practice, the importance of a group of features can be as high as the sum of the importances of the individual features in the group, or as low as zero in the rare case where what is learned for the correlated features actually cancels.  But cancellation is very rare, and usually we see the importance of a group of features is larger than the importance of the individual features in the group.

The second use of group importance is when you have a set of features, each of which may be weak individually, but which in aggregate can be important.  For example, in healthcare we sometimes want to know the importance of social effects such as income, education, geographic location (e.g., rural, suburban or urban), nearby access to medical care or a pharmacy, access to WiFi, access to transportation, etc.  In practice, no one of these factors is very strong.  But in aggregate they can be very important.  Group importance allows us to measure the importance of a set of features and see how important they are in aggregate.  Often there is overlap between these two uses because features that logically belong together in a set also tend to be correlated with each other, but the motivation for the two uses is different.

**Comment by master032** [comment]
> Hi @master032 --
> 
> There are two reasons for having term/feature group importances. One is that features can often be corelated with one another, and that creates problems for all methods when calculating the importance of the features individually. Let's say that I have two positively correlated features. In fact, to illustrate, imagine that we took one feature and we made an exact copy of it in our dataset. There isn't a perfect way to handle this situation since you can tradeoff importance between the two features without any change in the predictions, but the EBM will generally handle this by splitting up the contribution equally between these two features. The end result is that each feature will have half the feature importance that it would if we had eliminated one of the duplicates. This is an example of extreme/perfect correlation, but a similar problem occurs whenever there is strong correlation among a group of features, which there often is.
> 
> Group importance can partly resolve this by grouping features together that you suspect are correlated. Note that group importance does not change the prediction of the model in any way, it just adds groups of features to the summary of feature importance. In practice, the importance of a group of features can be as high as the sum of the importances of the individual features in the group, or as low as zero in the rare case where what is learned for the correlated features actually cancels. But cancellation is very rare, and usually we see the importance of a group of features is larger than the importance of the individual features in the group.
> 
> The second use of group importance is when you have a set of features, each of which may be weak individually, but which in aggregate can be important. For example, in healthcare we sometimes want to know the importance of social effects such as income, education, geographic location (e.g., rural, suburban or urban), nearby access to medical care or a pharmacy, access to WiFi, access to transportation, etc. In practice, no one of these factors is very strong. But in aggregate they can be very important. Group importance allows us to measure the importance of a set of features and see how important they are in aggregate. Often there is overlap between these two uses because features that logically belong together in a set also tend to be correlated with each other, but the motivation for the two uses is different.

Thank you for your detailed answer, I have a general idea about the importance of subset of ebm. Finally, could you explain how local importance in EBM is calculated? Thanks!

**Comment by paulbkoch** [comment]
For each feature in your sample, lookup what the global graph indicates is the score (y-axis) at the sample's feature value (x-axis).  That's the local importance.  It's also the value that we add up to make the prediction.  For a more programmatic version, it's the value in the term_score_ attribute for the bin corresponding to the feature value of a sample.
