### ISSUE TITLE
Question about the new attribute `term_scores_`

### ISSUE THREAD

**Issue by xiaohk** [interpretml/interpret#415]
Hey 👋, I'm updating [GAM Changer](https://github.com/interpretml/gam-changer) to use the new names introduced in [v0.3.0](https://github.com/interpretml/interpret/releases/tag/v0.3.0).

The old attribute `additive_terms_` has been renamed to `term_scores_`. I also notice it became one element longer.

For continuous variables, say we have a term `feature_1` with index 1.

```python
feature_1_bin_labels=  [3.0, 3.25, 17.75, 32.0]                               
                         |    -----------   |                                  
                         |         |        |                                  
         feature_bounds_[0]      bins       feature_bounds_[1]                 
      
# Old scores
model.additive_terms_[1] =  [0.0, 1.2065, -6.03280, -6.0328]

# New scores
model.term_scores_[1] =  [0.0, 1.2065, -6.03280, -6.0328, 0.0]                             
```

I remember these three values (`1.2065, -6.03280, -6.0328`) correspond to the three gaps in `feature_1_bin_labels` (e.g., [3.0,3.25), [3.25, 17.75), and [17,75, 32.0]). The first value `0.0` means the score for the missing value bin. What about the new `0.0` at the end of `feature_1_term_scores_`? Is it always 0?

For nominal and interaction terms, there are also 0 in the end of `term_scores_` in each dimension. For example, if the `additive_term_` for an interaction term has shape (3, 4). It seems the new `term_scores_`'s shape becomes (4, 5). Do these ending zeros have the same meaning as the continuous terms? Thank you!

**Comment by paulbkoch** [comment]
Hi @xiaohk -- I'll send you an email shortly with the details of this and other changes in v0.3.0, but to answer your question here quickly for other people viewing it later:

That last bin at the end is the new "unknown" bin.  It's not completely new actually since we've had this concept in Differentially Private EBMs since their release as this bin is required for DPEBMs, but in v0.3.0 we unified the concept with regular EBMs.

It's easiest to describe what 'unknown' is in the context of categoricals.  If during training we have some set of categorical values, eg: "Hawaii", "Texas", "California", but our testing set has some samples that have a new location like "Washington", what should we do?  Most models would raise an error, but with EBMs we have some additional options.  Since each feature is zero centered during fitting, using a score of zero is equivalent to simply ignoring that feature.  So, one option is we could set the score to zero in such a scenario for that feature.  That's what we used to do prior to v0.3.0.  In v0.3.0 we now return the value in that last bin, which is reserved for it.  This gives us maximum flexibility as we can fill it by default with zero, or we could set it to NaN to trigger an error condition, or we could try and learn what a feature having high arity means by putting all the categoricals with only 1 value into the 'unknown' bin, or we could let the end user edit it to whatever they want.

Today you can get a non-zero value in that bin if you train a DPEBM that has a high arity categorical.  Allowing categories with just 1 or a few samples would leak privacy information otherwise.  Even recording the category string would leak information, so we don't do it.  In the future I'll probably add a feature to regular EBMs to put categories that have just 1 or a few samples into the unknown bin, since they're basically useless anyways having just 1 sample to learn from.

The extra bin in the context of continuous values is also for the unknown bin.  For continuous features it's mostly there to simplify the model in that the same bin structure is consistent between categorical and continuous features.  It does still have a minor use though in that we use that bin if we receive a value that cannot be converted into a floating point number.  If you tried to predict the string "BAD_VALUE" for instance on a continuous feature, it would use the unknown bin.  In the future I'll probably make this bin by default NaN to trigger an error.  The model creator could then edit the model afterwards if they wish to allow such conditions.

**Comment by xiaohk** [comment]
Thank you so much! ❤️ I like the new "unknown" bin!
