### ISSUE TITLE
interpret -> interpret.core dependency

### ISSUE THREAD

**Issue by ashenfad** [interpretml/interpret#419]
A project of mine pinned `interpret==0.2.7` but since the dep range here is a little loose:

https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret/setup.py#L51-L53

I ended up with `interpret-core==0.3.2`, broken CI, and some lost time until I noticed the mismatch. Could the above range be tightened to something like `~=` to reduce surprises?

**Comment by ashenfad** [comment]
Nevermind - realized it's already fixed... just not for `0.2.7`. Closing.

**Comment by paulbkoch** [comment]
Sorry about the confusion @ashenfad -- Yes, this has been fixed in 0.3.2, but that won't help previous version pins.  If you want to continue pinning 0.2.7, you can do the following which should be functionally equivalent:

interpret-core[required,debug,notebook,plotly,lime,sensitivity,shap,ebm,linear,decisiontree,treeinterpreter,dash,skoperules,testing]==0.2.7
