### ISSUE TITLE
Attribute error:  Can't get attribute 'EBMPreprocessor' on 

### ISSUE THREAD

**Issue by Jebin1999** [interpretml/interpret#422]
I was loading a model in a pickle file, and I got this error: AttributeError: Can't get attribute 'EBMPreprocessor' on <module 'interpret.glassbox.ebm.ebm' from '/Users/opt/anaconda3/lib/python3.9/site-packages/interpret/glassbox/ebm/ebm.py'>

I tried using the older versions of interpret too, but the same error continues.

**Comment by paulbkoch** [comment]
Hi @Jebin1999 -- Do you know for sure what version of Interpret this pickle file was created with?  You'll probably need to get the version exactly right for pickle to work.  The one thing I can tell you is that the version was 0.2.7 or lower since EBMPreprocessor doesn't exists in that location for 0.3.x.
