### ISSUE TITLE
Does not work with timeseries data

### ISSUE THREAD

**Issue by darrahts** [interpretml/interpret#433]
Getting the error
`
ValueError: X must have 2 dimensions, but has 3
`
My data shape is (n_samples, n_timesteps, n_features), and (n_out,) for y. When I try to pass just `X[0]` and `y[0]` I get an error that X and y do not have the same length. This might be a feature request, just looking for more insight. 

Thanks!

**Comment by onacrame** [comment]
It seems you’re treating it as a tensor that would be more akin to how it may be set up for a neural network.  With tabular data that has a time series element when using these types of libraries I usually have the time series features in each row of data so that it’s all expressed in two dimensions and that works just fine.

**Comment by paulbkoch** [comment]
Hi @darrahts -- EBMs are currently a tabular ML method, so your data input needs to be in a 2D array format.  In my experience, timeseries data doesn't have one size fits all solutions that would fit neatly into a single API, although @onacrame's suggestion might work in many cases.  If you have specific suggestions, I'd be interested in hearing them though.
