### ISSUE TITLE
New release (0.4.0): Error trying to load ebm from registry

### ISSUE THREAD

**Issue by oceane-xomnia** [interpretml/interpret#437]
Before the new release (0.4.0), I had working ebm models saved in my mlflow registry. The new release makes me unable to load these models from the registry. I get the following error:

`No module named 'interpret.glassbox.ebm'`

Downgrading the package resolves the issue. Can this be fixed in the new release too?

**Comment by paulbkoch** [comment]
Hi @oceane-xomnia -- I believe mlflow by default uses cloudpickle to serialize models.  The issue with cloudpickle is that it doesn't guarantee that cross-version serialization of objects will be successful.  My understanding is that scikit-learn models have the same lack of guarantees, but perhaps it's less of an issue in practice for them since they are a more mature package where their internal attributes have been changing slower.  I think, but do not guarantee, that we've reached a point where our internal attributes should also change minimally in future releases, so perhaps this will be less of an issue for us as well going forward.

To solve this issue today, I think you have 3 potential solutions:
1) Convert the EBM to an Onnx model using [Ebm2Onnx](https://github.com/interpretml/ebm2onnx).  Onnx models should support long term storage, unlike cloudpickle.  The tradeoff is that you won't be able to visualize the Onnx models, but you should be able to predict with them in production environments.
2) Institute a process where you freeze the version used between building the model and predicting with them.  Any upgrade to the package will require a process to rebuild the EBMs.
3) You might, perhaps, maybe, be able to change the cloudpickle file to match the format of 0.4.0.  Version 0.4.0 had only a few changes from v0.3.0.  For example, interpret.glassbox.ebm is now exclusively under interpret.glassbox instead of before where it was duplicated in both interpret.glassbox.ebm and interpret.glassbox.

In the future we'll also support serialization of EBMs to JSON, which could then support cross-version serialization.  Currently we have code that allows you to serialize an EBM model to JSON, but not the reverse:

https://github.com/interpretml/interpret/blob/7098da67eef13b47e75116ed3bfa1de150d2a19e/python/interpret-core/interpret/glassbox/_ebm/_ebm.py#L1473
