### ISSUE TITLE
Supporting imbalanced classes better within glassbox models and adding support for feature -> importance map on global interpretability object

### ISSUE THREAD

**Issue by mturk24** [interpretml/interpret#439]
Hey there! I noticed in the ExplainableBoostingClassifier class (but also other classes used for classification) that you do not parametrize the class_weight param available in sklearn classifiers. This would be very useful for imbalanced class problems to have more control over. Would you be able to add more support for this?

Separately, I noticed when trying to access the global interpretability object (such as when calling .explain_global()), that you cannot easily access the map of features to importance values - if you can add an attribute that has this mapping easily accessible that would be useful for users.

**Comment by paulbkoch** [comment]
Hi @mturk24 -- We do support sample_weights on the fit function, which enables class weights at the cost of a little more verbosity:

```
sample_weights = np.empty(len(y))
sample_weights[y == 0] = 0.3
sample_weights[y == 1] = 0.7
```

Instead of calling .explain_global you can get the term importances directly by calling the "term_importances" function on the ExplainableBoostingClassifier object.  Here's a link to this function in our docs:

https://interpret.ml/docs/ebm.html#interpret.glassbox.ExplainableBoostingClassifier.term_importances

Here's some sample code to show how you'd use it:

```
from interpret.glassbox import ExplainableBoostingClassifier
ebm = ExplainableBoostingClassifier()
ebm.fit(X, y)
for name, importance in zip(ebm.term_names_, ebm.term_importances()):
    print(f"{name}: {importance}")
```
