### ISSUE TITLE
Can we distribute model training of EBM on pyspark?

### ISSUE THREAD

**Issue by Saurabhdhoble-8451** [interpretml/interpret#462]
Trying to understand if we can distribute the explainable boosting classifier model from InterpretML using joblib-spark which is a library to help activate backend of spark. Would that be feasible ? Trying to understand if we can distribute model training using spark to speed up training time

**Comment by paulbkoch** [comment]
Hi @Saurabhdhoble-8451 -- I'm not sure if it'll work or not, but I am pretty sure there won't be much benefit unless you are using a large number of outer bags, or potentially if you are hyperparameter tuning a number of EBMs.  We currently parallelize the work by training each outer bag on a core if you have enough cores to handle that.  Since outer_bags is set to 8 by default, we don't see a benefit beyond the 8th core on a processor today.  Improved parallelism is something we need to work on given increasing core counts.

One nice piece of news that I have for you is that the latest release, published 2-3 days ago, should be almost 3x faster when training for classification on Intel CPUs using the pypi install.

Another piece of good news, potentially, is that there is a group at Microsoft working on pure Synapse based EBM.  They're still in what I would call beta, but they've reached public preview from what I understand.  I'm sure they'd be interested in talking with you since they are looking for feedback on their implementation.  If you're interested in discussing this option with them, email us at interpret@microsoft.com and I'll put you in touch with them.

**Comment by Saurabhdhoble-8451** [comment]
@paulbkoch ..thanks for your response.Wanted to share some findings i have when was trying to understand how we could leverage spark to speed up model training time.I used an open source library called joblibspark. 
[
](https://github.com/joblib/joblib-spark)

This library provides Apache Spark backend for joblib to distribute tasks on a Spark cluster.I could significantly improve the model training time for EBM's with proper cluster configurations(drivers and workers).This library could help distribute the code over various workers.I did test on larger sample sets(100k-500k) and inner_bags=25 and outer_bags=50.

Example code:
with parallel_backend('spark',n_jobs=-1):
  explainer = ExplainableBoostingClassifier(n_jobs=64,inner_bags=25,outer_bags=50)
  # # Fit explainer
  ebm = explainer.fit(X_train, y_train)

explanation = explainer.explain_global(X_test)

**Comment by paulbkoch** [comment]
Thanks for the update @Saurabhdhoble-8451.  With 50 outer bags this makes sense, and I'm sure this information will be useful to others in the community as well.  We can continue the Spark EBM discussion in email.

**Comment by DaKlaas** [comment]
@Saurabhdhoble-8451  
What speedup did joblib-spark achieve?
