### ISSUE TITLE
Difference between EBM and interpretable blackbox using SHAP and LIME

### ISSUE THREAD

**Issue by basnetpro3** [interpretml/interpret#478]
If black box models can be interpreted using LIME and SHAP. What is the main difference between EBM and those black box models interpreted by SHAP and LIME? SHAP and LIME can also generate global and local explanations. What is the superiority of EBM over others?

**Comment by paulbkoch** [comment]
Hi @basnetpro3 -- Does this adequately answer your question:

https://github.com/interpretml/interpret/issues/471#issuecomment-1690955219

Another way to answer this question is to point out that tree models can be exactly represented as complicated EBMs.  The default XGBoost model is built with max_depth=6 and n_estimators=100, which means that there would be 2^5 * 100 = 3,200 potential 6-way interactions if you were to convert an XGBoost model into an EBM.  SHAP supports the computation of SHAP values for pairwise interaction terms (https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Basic%20SHAP%20Interaction%20Value%20Example%20in%20XGBoost.html), but it doesn't support anything beyond 2 dimensions, so the 6-way interactions in an XGBoost model are summarized via individual features instead.  EBM models remove this issue since we restrict the model to disallow 6-way interactions during construction and force it by default to use only a limited number of 2-way interactions that we can visualize.  Surprisingly, for tabular data using just main effects and pairwise terms seems to capture most of the predictive power of more complicated models.  We optionally support higher level interactions for scenarios where 2-way interactions are not sufficient, but we haven't seen a case yet where these are needed.

Another way to explain this is to point out that the global explanation graphs of an EBM can be used to make predictions by themselves.  If I were to give you a printout of each feature plot, you could calculate the output of the EBM model for any input.  You cannot do this from global SHAP plots because the SHAP plots are not a complete representation of the underlying model.

**Comment by paulbkoch** [comment]
There's a more in-depth handling of this question in:

https://arxiv.org/pdf/2209.04012.pdf

**Comment by basnetpro3** [comment]
Thank you very much! your answers are very satisfying.

**Comment by JWKKWJ123** [comment]
Thank you very much! I am also think about this recently. Your answer solved my question！

**Comment by paulbkoch** [comment]
Glad my answers made some sense. It's a subtle concept to convey.

Closing this issue for now but feel free to reopen if there are more questions on this topic.
