### ISSUE TITLE
NaNs cause hanging issue while training

### ISSUE THREAD

**Issue by hexgnu** [interpretml/interpret#67]
Hey there, thank you for this awesome project!

At first I thought this was an issue with joblib but found out it had to do with NaNs in my dataframe.

Problem: when I try and train using NaNs the job basically just hangs and is pegging only one core. It seems like a better case would be to return an error or something because I had no idea it was just hanging since #7 isn't implemented yet.

![image](https://user-images.githubusercontent.com/138510/65788257-ab46dc00-e128-11e9-833c-bdba9e34f1d7.png)

I am running Fedora 30 with python 3.7.3.

Perhaps a simple check for NaNs in the array would be useful as an error to prevent this from happening? Lemme know how I can help and thank you! Great speech at Strata btw

Thank you

-Matt

**Comment by interpret-ml** [comment]
Hi @hexgnu - glad you enjoyed the talk at Strata, we had a blast!

Thanks for reporting this. This is a bug on our part, we had some NA handling before release but decided to pull it.

You're welcome to submit a pull request throwing an exception on NaNs. Otherwise, we'll produce a fix on this around end of week.

**Comment by interpret-ml** [comment]
Hi @hexgnu - This issue has been fixed in our latest 0.1.19 release.  Thanks again for reporting this to us.

- InterpretML Team
