### ISSUE TITLE
EBM on Azure ML toolkit

### ISSUE THREAD

**Issue by fernandoramacciotti** [interpretml/interpret#84]
Hi all,

I was reading the [Model Interpretability article from Azure ML](https://docs.microsoft.com/en-us/azure/machine-learning/service/machine-learning-interpretability-explainability?ocid=AID2463683&wt.mc_id=ai-c9-sejuare#next-steps) and there is a lot in common with `interpret` package.

I have 2 questions:
1) what is the difference between classes from `interpret` and `interpret.ext`? I have seen that in the AzureML notebooks the `.ext` was used
2) Is it possible to use EBM on the AzureML toolkit? Does it make sense to use `TabularExplainer` on EBM since it is a glassbox model?

Thanks in advance,
Fernando

**Comment by interpret-ml** [comment]
Hi @fernandoramacciotti, 

Good eye! The interpret.ext namespace is an early design for an upcoming extension system. We're actively collaborating on this with the AzureML team, and we'll have more to say on this in the coming weeks. Stay tuned for more details :)!

-InterpretML Team

**Comment by imatiach-msft** [comment]
@fernandoramacciotti the azureml-explain-model package has been split into two parts, interpret-community, which has been open-sourced:
https://github.com/interpretml/interpret-community
and azureml-interpret, which interfaces with azure.  Interpret-commmunity is an extension of interpret, meaning that it is in the same namespace and has the same schema on explanations.  You can take a look at the notebooks in interpret-community for examples.

"Does it make sense to use TabularExplainer on EBM since it is a glassbox model?"
TabularExplainer is used to explain greybox/blackbox models, whereas EBM is itself an explainable "glassbox" model.  So it wouldn't make sense to use it on EBM because the explanation would be less accurate than the true explanation from EBM itself.
