### ISSUE TITLE
vignette for R

### ISSUE THREAD

**Issue by notast** [interpretml/interpret#97]
is it possible to provide a vignette for R for the jupyter notebooks written in python?

**Comment by interpret-ml** [comment]
Hi @notast --

Good eye in finding the R package.  We were hoping to keep it quiet for a bit longer since it's at an early stage of its development.  Right now the only real thing that you can do with it is build an EBM on mains (no pair interactions yet).  This could be useful for instance in measuring how EBMs perform vs any of the other available GAM packages, which mostly seem to reside in R.  The components for visualizing the results still need to be ported over.  We will continue to build out the R functionality and will have more to say about this soon.

**Comment by interpret-ml** [comment]
Hi @notast - The R package now includes some examples that should make it clearer how to use the package.  The interface has also changed substantially since the initial release.  Please have a look at:

https://cran.r-project.org/web/packages/interpret/interpret.pdf

-InterpretML team
