### ISSUE TITLE
Is it possible to add constraints such as the prediction should be positive?

### ISSUE THREAD

**Issue by hpsong88** [interpretml/interpret#98]
Hi,

I am using ebm for regression, and it is amazing. I am wondering if the model can add constraints as the prediction should be positive?

Thanks!

**Comment by richcaruana** [comment]
Hi,

Sorry for the very slow reply!  We don't currently have a way to add constraints like this to EBM regression.  Often the best way to handle this kind of constraint is to force any value that falls outside of the constraint (e.g., below 0.0 in this case) and then set it to zero.  If the values that the model predicts just above zero look distorted, then one might try something more complex such as applying a calibration-like transformation to the model's predictions near zero using a calibration method such as Isotonic Regression that can also handle constraints that the values have to be above zero.  But you wouldn't want to do this unless you saw clear distortion in the predicted values above (and near) zero.  Otherwise simple truncation probably is the best solution.  

Of course there are many settings where predictions below zero might not make sense.  For example if you are predicting the height, weight or cost of an object, it probably should have non-negative height, weight or cost.  Unless learning can learn the function perfectly, however, it is likely that there is some noise/error in the predicted values, and that this would sometimes allow predicted values to take on values that are not otherwise meaningful (e.g., negative).  But without a good understanding of the noise process, it's difficult to do better than truncation.  If, however, plotting a graph of predicted value vs. true value shows clear distortion for values that are not only impossible (negative), but for values that are possible but near the threshold, then it could make sense to apply post-model calibration to not only add the non-negativity constraint but to also correct the predictions that are legal but near the threshold.

Hope this helps!    -the InterpretML team.
